modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="toimmortality"
version="1.0"
displayName="Totem of immortality"
credits="tinytransfem"
displayURL="https://curseforge.com/minecraft/mc-mods/totem-of-immortality"
authors="tinytransfem"
logoFile="logo.png"
description='''Adds a totem that makes a player immortal while it's in the inventory.'''

[[dependencies.toimmortality]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,]"
ordering="NONE"
side="BOTH"